custom_css = """
<style>
    /* Replace 'Agency FB' with the desired font family */
    body {
        font-family: 'NanumGothic', sans-serif;
    }
</style>
"""

st.markdown(custom_css, unsafe_allow_html=True)